### CREAR EMPLEADO
POST http://localhost:3000/api/auth/empleados
Content-Type: application/json

{
  "folder":"folder1",
  "nombre": "Juan Perez",
  "fecha_nacimiento": "01/01/1980",
  "direccion": "123 Calle Principal",
  "telefono": "555-1234",
  "tipo_licencia": "Local",
  "nro_licencia": "ABC12345",
  "categoria": "A",
  "fecha_venc_licencia": "31/12/2025",
  "fecha_venc_rcontrol": "31/12/2024",
  "fecha_venc_exmedico": "31/12/2023",
  "file_licencia": true,
  "file_r_control": true,
  "file_examen_medico": true
}
### CREAR CLIENTE
POST http://localhost:3000/api/auth/clients
{
  "nombre":"Clientito",
  "direccion":"Av. San Francisco",
  "provincia":"Tonala",
  "distrito":"Itsmo costa",
  "telefono":"9661034332",
  "ruc":"jiji"
}